-- =====================================================================
-- CommerceOps · 13_edge_cases.sql   (dataset v1)
-- CONTROLLED ANOMALY LAB
--
-- Bu dosya ana seed'in PARCASI DEGILDIR ve ana seed'i bozmaz.
-- Amac: reconciliation ve data correction calismalari (Module 7 ve
-- buggy query review programi) icin BELGELENMIS, RESETLENEBILIR
-- is-kurali ihlalleri uretmek.
--
-- Onemli ayrim:
--   * Ana seed  -> "valid but tricky": NULL, zero-child parent, ayni
--                  timestamp, coklu payment attempt, partial refund,
--                  split shipment. Hepsi YASAL veridir.
--   * Bu dosya  -> "controlled anomaly": constraint'leri ihlal etmeyen
--                  ama BUSINESS kurallarini ihlal eden kayitlar.
--
-- Idempotent: dosyayi tekrar calistirmak once onceki lab kayitlarini
-- siler, sonra yeniden uretir. Sadece INSERT yapar; mevcut seed
-- satirlarini asla UPDATE etmez.
--
-- Temizlemek icin:  SELECT commerceops.lab_reset();
-- =====================================================================

SET search_path = commerceops, public;

CREATE TABLE IF NOT EXISTS lab_objects (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_case   text        NOT NULL,
    table_name text        NOT NULL,
    row_id     bigint      NOT NULL,
    note       text,
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE lab_objects IS 'Anomaly lab kayit defteri. Reset bu tabloya gore yapilir.';

-- ---------------------------------------------------------------------
-- Reset: kayitli lab satirlarini FK'ye guvenli sirayla siler
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION lab_reset()
RETURNS text
LANGUAGE plpgsql
SET search_path = commerceops, public
AS $$
DECLARE
    r          record;
    deleted    integer := 0;
    tbl_order  text[] := ARRAY['reviews','shipment_items','shipments','inventory_movements',
                               'refunds','payments','order_status_history','order_items',
                               'orders','merchant_members'];
    t          text;
    n          integer;
BEGIN
    FOREACH t IN ARRAY tbl_order LOOP
        FOR r IN SELECT row_id FROM lab_objects WHERE table_name = t LOOP
            EXECUTE format('DELETE FROM commerceops.%I WHERE id = $1', t) USING r.row_id;
            GET DIAGNOSTICS n = ROW_COUNT;
            deleted := deleted + n;
        END LOOP;
    END LOOP;
    DELETE FROM lab_objects;
    RETURN format('%s lab satiri silindi.', deleted);
END;
$$;

SELECT lab_reset();

-- ---------------------------------------------------------------------
-- Lab senaryolarini uret
-- ---------------------------------------------------------------------
DO $lab$
DECLARE
    v_user      bigint;
    v_user2     bigint;
    v_merchant  bigint;
    v_product   bigint;
    v_product2  bigint;
    v_warehouse bigint;
    v_order     bigint;
    v_item      bigint;
    v_shipment  bigint;
    v_payment   bigint;
    v_ship_item bigint;
    v_row       bigint;
    v_base      timestamptz := '2026-05-04 10:00:00+00';
BEGIN
    SELECT id INTO v_user  FROM users  WHERE status = 'ACTIVE' ORDER BY id LIMIT 1;
    SELECT id INTO v_user2 FROM users  WHERE status = 'ACTIVE' ORDER BY id OFFSET 7 LIMIT 1;
    SELECT w.id, w.merchant_id INTO v_warehouse, v_merchant
    FROM warehouses w WHERE w.is_active ORDER BY w.id LIMIT 1;
    SELECT id INTO v_product  FROM products WHERE merchant_id = v_merchant AND status = 'ACTIVE' ORDER BY id LIMIT 1;
    SELECT id INTO v_product2 FROM products WHERE merchant_id = v_merchant AND status = 'ACTIVE' ORDER BY id OFFSET 1 LIMIT 1;
    IF v_product2 IS NULL THEN v_product2 := v_product; END IF;

    -- =================================================================
    -- LAB-01 · Over-shipment
    -- Order item quantity'sinden FAZLA quantity gonderilmis.
    -- Beklenen bulgu: shipment completion query'si "fazla gonderilmis"
    -- item'lari da yakalamali; sadece "eksik" aramak yetmez.
    -- =================================================================
    INSERT INTO orders (order_number, customer_id, status, currency, placed_at, created_at, updated_at,
                        ship_recipient_name, ship_line1, ship_city, ship_postal_code, ship_country_code)
    VALUES ('LAB-01-OVERSHIP', v_user, 'DELIVERED', 'TRY', v_base, v_base, v_base + interval '3 days',
            'Lab Recipient', 'Lab Sok. No:1', 'Istanbul', '34000', 'TR')
    RETURNING id INTO v_order;
    INSERT INTO lab_objects(lab_case, table_name, row_id, note)
        VALUES ('LAB-01','orders', v_order, 'Over-shipment senaryosunun order kaydi');

    INSERT INTO order_items (order_id, product_id, merchant_id, quantity, unit_price, discount_amount, created_at)
    VALUES (v_order, v_product, v_merchant, 2, 250.00, 0, v_base)
    RETURNING id INTO v_item;
    INSERT INTO lab_objects(lab_case, table_name, row_id, note)
        VALUES ('LAB-01','order_items', v_item, 'quantity=2 siparis edildi');

    INSERT INTO shipments (order_id, warehouse_id, carrier, tracking_code, status, shipped_at, delivered_at, created_at)
    VALUES (v_order, v_warehouse, 'ARAS', 'TRK-LAB-0000000001', 'DELIVERED',
            v_base + interval '1 day', v_base + interval '3 days', v_base)
    RETURNING id INTO v_shipment;
    INSERT INTO lab_objects(lab_case, table_name, row_id, note)
        VALUES ('LAB-01','shipments', v_shipment, NULL);

    INSERT INTO shipment_items (shipment_id, order_item_id, quantity)
    VALUES (v_shipment, v_item, 5)          -- 2 siparis, 5 gonderim
    RETURNING id INTO v_ship_item;
    INSERT INTO lab_objects(lab_case, table_name, row_id, note)
        VALUES ('LAB-01','shipment_items', v_ship_item, 'ANOMALI: 5 > 2');

    -- =================================================================
    -- LAB-02 · Refund total > payment amount
    -- Tek payment'a bagli iki COMPLETED refund toplami payment tutarini asiyor.
    -- Beklenen bulgu: net revenue negatife duser; gross/net karsilastirmasi
    -- yapan reporting query'si bunu yakalamali.
    -- =================================================================
    INSERT INTO orders (order_number, customer_id, status, currency, placed_at, created_at, updated_at,
                        ship_recipient_name, ship_line1, ship_city, ship_postal_code, ship_country_code)
    VALUES ('LAB-02-OVERREFUND', v_user, 'DELIVERED', 'TRY', v_base, v_base, v_base + interval '2 days',
            'Lab Recipient', 'Lab Sok. No:2', 'Ankara', '06000', 'TR')
    RETURNING id INTO v_order;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-02','orders', v_order, NULL, DEFAULT);

    INSERT INTO order_items (order_id, product_id, merchant_id, quantity, unit_price, discount_amount, created_at)
    VALUES (v_order, v_product, v_merchant, 1, 400.00, 0, v_base)
    RETURNING id INTO v_item;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-02','order_items', v_item, NULL, DEFAULT);

    INSERT INTO payments (order_id, provider, attempt_no, status, amount, currency, created_at, settled_at, provider_response)
    VALUES (v_order, 'ADYEN', 1, 'SUCCEEDED', 400.00, 'TRY', v_base + interval '5 minutes',
            v_base + interval '8 minutes', '{"provider_ref":"PR-LAB-02","risk_score":3}'::jsonb)
    RETURNING id INTO v_payment;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-02','payments', v_payment, 'amount=400', DEFAULT);

    INSERT INTO refunds (payment_id, order_item_id, amount, reason, status, created_at, processed_at)
    VALUES (v_payment, v_item, 300.00, 'DAMAGED', 'COMPLETED', v_base + interval '4 days', v_base + interval '4 days')
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-02','refunds', v_row, 'ilk refund 300', DEFAULT);

    INSERT INTO refunds (payment_id, order_item_id, amount, reason, status, created_at, processed_at)
    VALUES (v_payment, v_item, 250.00, 'WRONG_ITEM', 'COMPLETED', v_base + interval '9 days', v_base + interval '9 days')
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-02','refunds', v_row, 'ANOMALI: 300+250 > 400', DEFAULT);

    -- =================================================================
    -- LAB-03 · DELIVERED order, basarili payment yok
    -- Beklenen bulgu: fulfillment raporu ile revenue raporu ayni order'i
    -- farkli sekilde sayar. "Teslim edildi ama parasi alinmadi."
    -- =================================================================
    INSERT INTO orders (order_number, customer_id, status, currency, placed_at, created_at, updated_at,
                        ship_recipient_name, ship_line1, ship_city, ship_postal_code, ship_country_code)
    VALUES ('LAB-03-UNPAID-DELIVERED', v_user2, 'DELIVERED', 'TRY', v_base, v_base, v_base + interval '4 days',
            'Lab Recipient', 'Lab Sok. No:3', 'Izmir', '35000', 'TR')
    RETURNING id INTO v_order;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-03','orders', v_order, 'ANOMALI: DELIVERED ama SUCCEEDED payment yok', DEFAULT);

    INSERT INTO order_items (order_id, product_id, merchant_id, quantity, unit_price, discount_amount, created_at)
    VALUES (v_order, v_product2, v_merchant, 3, 120.00, 0, v_base)
    RETURNING id INTO v_item;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-03','order_items', v_item, NULL, DEFAULT);

    INSERT INTO payments (order_id, provider, attempt_no, status, amount, currency, created_at, failure_code)
    VALUES (v_order, 'STRIPE', 1, 'FAILED', 360.00, 'TRY', v_base + interval '10 minutes', 'DO_NOT_HONOR')
    RETURNING id INTO v_payment;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-03','payments', v_payment, 'sadece FAILED attempt', DEFAULT);

    -- =================================================================
    -- LAB-04 · Celiskili membership
    -- is_active = true fakat ended_at gecmis tarihte.
    -- Beklenen bulgu: authorization query'si sadece is_active'e bakarsa
    -- yetkisi bitmis kullaniciya erisim verir (authorization leakage).
    -- =================================================================
    INSERT INTO merchant_members (merchant_id, user_id, role, is_active, joined_at, ended_at)
    SELECT v_merchant, u.id, 'MANAGER', true, '2025-02-01 09:00:00+00', '2025-11-30 18:00:00+00'
    FROM users u
    WHERE u.status = 'ACTIVE'
      AND NOT EXISTS (SELECT 1 FROM merchant_members mm
                      WHERE mm.merchant_id = v_merchant AND mm.user_id = u.id)
    ORDER BY u.id
    LIMIT 1
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-04','merchant_members', v_row,
        'ANOMALI: is_active=true ama ended_at gecmiste', DEFAULT);

    -- =================================================================
    -- LAB-05 · Negatif on-hand (inventory drift)
    -- Karsiligi olmayan buyuk OUTBOUND hareketi.
    -- Beklenen bulgu: SUM(quantity) negatif; reconciliation gerekir.
    -- =================================================================
    INSERT INTO inventory_movements (warehouse_id, product_id, movement_type, quantity, occurred_at,
                                     reference_type, reference_id, metadata, created_at)
    VALUES (v_warehouse, v_product, 'OUTBOUND', -99999, v_base + interval '6 days',
            'SHIPMENT_ITEM', 999999999,
            '{"note":"lab: karsiligi olmayan cikis","source":"LAB"}'::jsonb, v_base + interval '6 days')
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-05','inventory_movements', v_row,
        'ANOMALI: reference_id gecersiz, on-hand negatife duser', DEFAULT);

    -- =================================================================
    -- LAB-06 · Bozuk status history
    -- (a) placed_at''ten ONCE gerceklesmis status degisikligi
    -- (b) atlanmis ara status (PENDING -> DELIVERED)
    -- Beklenen bulgu: "latest status" query'si ORDER BY changed_at ile
    -- yanlis satiri secebilir; deterministic tie-breaker gerekir.
    -- =================================================================
    INSERT INTO orders (order_number, customer_id, status, currency, placed_at, created_at, updated_at,
                        ship_recipient_name, ship_line1, ship_city, ship_postal_code, ship_country_code)
    VALUES ('LAB-06-BROKEN-HISTORY', v_user, 'DELIVERED', 'TRY', v_base, v_base, v_base + interval '5 days',
            'Lab Recipient', 'Lab Sok. No:6', 'Bursa', '16000', 'TR')
    RETURNING id INTO v_order;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-06','orders', v_order, NULL, DEFAULT);

    INSERT INTO order_items (order_id, product_id, merchant_id, quantity, unit_price, discount_amount, created_at)
    VALUES (v_order, v_product, v_merchant, 1, 199.90, 0, v_base)
    RETURNING id INTO v_item;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-06','order_items', v_item, NULL, DEFAULT);

    INSERT INTO order_status_history (order_id, from_status, to_status, changed_at, note)
    VALUES (v_order, NULL, 'PENDING', v_base - interval '2 hours', 'ANOMALI: placed_at oncesi')
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-06','order_status_history', v_row, NULL, DEFAULT);

    INSERT INTO order_status_history (order_id, from_status, to_status, changed_at, note)
    VALUES (v_order, 'PENDING', 'DELIVERED', v_base + interval '2 days', 'ANOMALI: ara statusler atlanmis')
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-06','order_status_history', v_row, NULL, DEFAULT);

    INSERT INTO order_status_history (order_id, from_status, to_status, changed_at, note)
    VALUES (v_order, 'PENDING', 'SHIPPED', v_base + interval '2 days', 'ANOMALI: ayni changed_at, celiskili kayit')
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-06','order_status_history', v_row, NULL, DEFAULT);

    -- =================================================================
    -- LAB-07 · Item'i olmayan order
    -- Beklenen bulgu: order total 0 mi NULL mi? INNER JOIN ile order
    -- listesinden tamamen kaybolur.
    -- =================================================================
    INSERT INTO orders (order_number, customer_id, status, currency, placed_at, created_at, updated_at,
                        ship_recipient_name, ship_line1, ship_city, ship_postal_code, ship_country_code)
    VALUES ('LAB-07-EMPTY-ORDER', v_user2, 'PAID', 'TRY', v_base, v_base, v_base,
            'Lab Recipient', 'Lab Sok. No:7', 'Antalya', '07000', 'TR')
    RETURNING id INTO v_order;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-07','orders', v_order, 'ANOMALI: hic order_item yok', DEFAULT);

    INSERT INTO payments (order_id, provider, attempt_no, status, amount, currency, created_at, settled_at)
    VALUES (v_order, 'WALLET', 1, 'SUCCEEDED', 0.00, 'TRY', v_base + interval '3 minutes', v_base + interval '4 minutes')
    RETURNING id INTO v_payment;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-07','payments', v_payment, 'amount=0', DEFAULT);

    -- =================================================================
    -- LAB-08 · Zaman tutarsizligi: payment order''dan once settle olmus
    -- Beklenen bulgu: tarih araligi raporlarinda order ayi ile payment ayi
    -- ayrisir; hangi timestamp''e gore raporlandigi kritik hale gelir.
    -- =================================================================
    INSERT INTO orders (order_number, customer_id, status, currency, placed_at, created_at, updated_at,
                        ship_recipient_name, ship_line1, ship_city, ship_postal_code, ship_country_code)
    VALUES ('LAB-08-TIME-SKEW', v_user, 'PAID', 'TRY', v_base, v_base, v_base,
            'Lab Recipient', 'Lab Sok. No:8', 'Konya', '42000', 'TR')
    RETURNING id INTO v_order;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-08','orders', v_order, NULL, DEFAULT);

    INSERT INTO order_items (order_id, product_id, merchant_id, quantity, unit_price, discount_amount, created_at)
    VALUES (v_order, v_product2, v_merchant, 2, 75.50, 0, v_base)
    RETURNING id INTO v_item;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-08','order_items', v_item, NULL, DEFAULT);

    INSERT INTO payments (order_id, provider, attempt_no, status, amount, currency, created_at, settled_at)
    VALUES (v_order, 'LOCAL_BANK', 1, 'SUCCEEDED', 151.00, 'TRY',
            v_base - interval '40 days', v_base - interval '40 days' + interval '5 minutes')
    RETURNING id INTO v_payment;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-08','payments', v_payment,
        'ANOMALI: settled_at, order placed_at''ten 40 gun once', DEFAULT);

    -- =================================================================
    -- LAB-09 · Satin alinmamis urune "verified" review
    -- Beklenen bulgu: is_verified alanina guvenmek yanlis; dogrulama
    -- order_items uzerinden EXISTS ile yapilmali.
    -- =================================================================
    INSERT INTO reviews (product_id, user_id, order_item_id, rating, title, body, is_verified, submitted_at, created_at)
    SELECT p.id, v_user2, NULL, 5, 'Lab review', 'Satin alinmamis urune verified review.', true,
           (v_base + interval '7 days') AT TIME ZONE 'UTC', v_base + interval '7 days'
    FROM products p
    WHERE p.status = 'ACTIVE'
      AND NOT EXISTS (SELECT 1 FROM order_items oi
                      JOIN orders o ON o.id = oi.order_id
                      WHERE oi.product_id = p.id AND o.customer_id = v_user2)
      AND NOT EXISTS (SELECT 1 FROM reviews r WHERE r.product_id = p.id AND r.user_id = v_user2)
    ORDER BY p.id
    LIMIT 1
    RETURNING id INTO v_row;
    INSERT INTO lab_objects VALUES (DEFAULT,'LAB-09','reviews', v_row,
        'ANOMALI: is_verified=true ama satin alma kaydi yok', DEFAULT);

    RAISE NOTICE 'Anomaly lab yuklendi.';
END;
$lab$;

-- ---------------------------------------------------------------------
-- Yuklenen lab senaryolarinin ozeti
-- ---------------------------------------------------------------------
SELECT lab_case,
       count(*) AS row_count,
       string_agg(DISTINCT table_name, ', ' ORDER BY table_name) AS tables
FROM lab_objects
GROUP BY lab_case
ORDER BY lab_case;
