-- =====================================================================
-- CommerceOps · 14_verify_seed.sql   (dataset v1)
--
-- Seed dogrulama. Iki tur kontrol yapar:
--
--   A) STRUCTURAL  — veri tutarli mi? (constraint'lerin yakalamadigi
--                    business invariant'lar)
--   B) TEACHING    — dataset ogretmeye uygun mu? (zero-child parent,
--                    hic satilmamis urun, ayni timestamp, split
--                    shipment, failed->succeeded payment ...)
--
-- (B) kontrolleri (A) kadar onemlidir: bu ozellikler yoksa modullerdeki
-- LEFT JOIN, NULL, inflation ve pagination dersleri calismaz.
--
-- Anomaly lab (13_edge_cases.sql) kayitlari dogrulamadan HARIC tutulur.
--
-- Kullanim:  psql -v ON_ERROR_STOP=1 -f 14_verify_seed.sql
--            veya   SELECT * FROM commerceops.verify_seed();
-- =====================================================================

SET search_path = commerceops, public;

-- Lab kayit defteri henuz yoksa bos olarak olustur (verify ona bakar)
CREATE TABLE IF NOT EXISTS lab_objects (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_case   text        NOT NULL,
    table_name text        NOT NULL,
    row_id     bigint      NOT NULL,
    note       text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION verify_seed()
RETURNS TABLE (kind text, check_name text, actual bigint, ok boolean, note text)
LANGUAGE sql STABLE
SET search_path = commerceops, public
AS $$
WITH prof AS (
    SELECT profile, dataset_version FROM dataset_info WHERE id = 1
),
lab_orders AS (
    SELECT row_id FROM lab_objects WHERE table_name = 'orders'
),
lab_ship_items AS (
    SELECT row_id FROM lab_objects WHERE table_name = 'shipment_items'
),
lab_refunds AS (
    SELECT row_id FROM lab_objects WHERE table_name = 'refunds'
),
expected AS (
    SELECT CASE WHEN (SELECT profile FROM prof) = 'small' THEN 12000 ELSE 400000 END AS order_count
)
-- =============== A) STRUCTURAL =====================================
SELECT 'STRUCTURAL', 'dataset_info tek satir', count(*)::bigint, count(*) = 1,
       'profile=' || COALESCE((SELECT profile FROM prof),'YOK') ||
       ' version=' || COALESCE((SELECT dataset_version FROM prof),'YOK')
FROM dataset_info
UNION ALL
SELECT 'STRUCTURAL', 'order sayisi profile ile uyumlu', count(*)::bigint,
       count(*) = (SELECT order_count FROM expected),
       'beklenen ' || (SELECT order_count FROM expected)
FROM orders WHERE id NOT IN (SELECT row_id FROM lab_orders)
UNION ALL
SELECT 'STRUCTURAL', 'her order en az 1 item icerir', count(*)::bigint, count(*) = 0,
       'item''i olmayan order sayisi'
FROM orders o
WHERE o.id NOT IN (SELECT row_id FROM lab_orders)
  AND NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id)
UNION ALL
SELECT 'STRUCTURAL', 'SUCCEEDED payment settled_at dolu', count(*)::bigint, count(*) = 0, 'ihlal sayisi'
FROM payments WHERE status = 'SUCCEEDED' AND settled_at IS NULL
UNION ALL
SELECT 'STRUCTURAL', 'SUCCEEDED olmayan payment settled_at NULL', count(*)::bigint, count(*) = 0, 'ihlal sayisi'
FROM payments WHERE status <> 'SUCCEEDED' AND settled_at IS NOT NULL
UNION ALL
SELECT 'STRUCTURAL', 'order basina en fazla 1 SUCCEEDED payment', count(*)::bigint, count(*) = 0,
       'birden fazla basarili odemesi olan order'
FROM (SELECT order_id FROM payments WHERE status = 'SUCCEEDED'
      GROUP BY order_id HAVING count(*) > 1) x
UNION ALL
SELECT 'STRUCTURAL', 'refund toplami payment tutarini asmaz', count(*)::bigint, count(*) = 0, 'ihlal sayisi'
FROM (SELECT r.payment_id
      FROM refunds r
      JOIN payments p ON p.id = r.payment_id
      WHERE r.status = 'COMPLETED'
        AND r.id NOT IN (SELECT row_id FROM lab_refunds)
      GROUP BY r.payment_id, p.amount
      HAVING sum(r.amount) > p.amount) y
UNION ALL
SELECT 'STRUCTURAL', 'shipment quantity order quantity''yi asmaz', count(*)::bigint, count(*) = 0, 'ihlal sayisi'
FROM (SELECT si.order_item_id
      FROM shipment_items si
      JOIN order_items oi ON oi.id = si.order_item_id
      WHERE si.id NOT IN (SELECT row_id FROM lab_ship_items)
      GROUP BY si.order_item_id, oi.quantity
      HAVING sum(si.quantity) > oi.quantity) z
UNION ALL
SELECT 'STRUCTURAL', 'order_item.merchant_id product ile tutarli', count(*)::bigint, count(*) = 0, 'ihlal sayisi'
FROM order_items oi JOIN products p ON p.id = oi.product_id
WHERE oi.merchant_id <> p.merchant_id
UNION ALL
SELECT 'STRUCTURAL', 'her order''in en az 1 status history kaydi var', count(*)::bigint, count(*) = 0, 'eksik order'
FROM orders o
WHERE o.id NOT IN (SELECT row_id FROM lab_orders)
  AND NOT EXISTS (SELECT 1 FROM order_status_history h WHERE h.order_id = o.id)
UNION ALL
SELECT 'STRUCTURAL', 'category hierarchy cycle icermez', count(*)::bigint, count(*) = 0, 'kendini parent alan kayit'
FROM categories WHERE parent_id = id

-- =============== B) TEACHING PROPERTIES =============================
UNION ALL
SELECT 'TEACHING', 'hic siparis vermemis user var', count(*)::bigint, count(*) > 0,
       'LEFT JOIN / zero-child parent calismasi'
FROM users u WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = u.id)
UNION ALL
SELECT 'TEACHING', 'hic satilmamis ACTIVE product var', count(*)::bigint, count(*) > 0,
       'NOT EXISTS / anti-join calismasi'
FROM products p
WHERE p.status = 'ACTIVE'
  AND NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = p.id)
UNION ALL
SELECT 'TEACHING', 'hic urunu olmayan merchant var', count(*)::bigint, count(*) > 0, 'zero-child parent'
FROM merchants m WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.merchant_id = m.id)
UNION ALL
SELECT 'TEACHING', 'hic review almamis product var', count(*)::bigint, count(*) > 0, 'LEFT JOIN + NULL'
FROM products p WHERE NOT EXISTS (SELECT 1 FROM reviews r WHERE r.product_id = p.id)
UNION ALL
SELECT 'TEACHING', 'birden fazla merchant iceren order var', count(*)::bigint, count(*) > 0,
       'merchant subtotal vs order total ayrimi'
FROM (SELECT order_id FROM order_items GROUP BY order_id HAVING count(DISTINCT merchant_id) > 1) a
UNION ALL
SELECT 'TEACHING', 'once FAILED sonra SUCCEEDED payment var', count(*)::bigint, count(*) > 0,
       'latest attempt / conditional aggregation'
FROM (SELECT order_id FROM payments GROUP BY order_id
      HAVING count(*) FILTER (WHERE status = 'FAILED') > 0
         AND count(*) FILTER (WHERE status = 'SUCCEEDED') > 0) b
UNION ALL
SELECT 'TEACHING', 'hic payment kaydi olmayan order var', count(*)::bigint, count(*) > 0, 'LEFT JOIN + NULL'
FROM orders o WHERE NOT EXISTS (SELECT 1 FROM payments p WHERE p.order_id = o.id)
UNION ALL
SELECT 'TEACHING', 'birden fazla shipment''a bolunmus order var', count(*)::bigint, count(*) > 0,
       'cross multiplication / inflation'
FROM (SELECT order_id FROM shipments GROUP BY order_id HAVING count(*) > 1) c
UNION ALL
SELECT 'TEACHING', 'kismi gonderilmis order item var', count(*)::bigint, count(*) > 0,
       'shipment completion dogrulamasi'
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE o.status IN ('SHIPPED','DELIVERED')
  AND COALESCE((SELECT sum(si.quantity) FROM shipment_items si WHERE si.order_item_id = oi.id), 0) < oi.quantity
UNION ALL
SELECT 'TEACHING', 'ayni placed_at degerini paylasan order gruplari', count(*)::bigint, count(*) > 0,
       'keyset pagination tie-breaker'
FROM (SELECT placed_at FROM orders GROUP BY placed_at HAVING count(*) > 1) d
UNION ALL
SELECT 'TEACHING', 'partial refund var', count(*)::bigint, count(*) > 0, 'gross vs net revenue'
FROM refunds r JOIN payments p ON p.id = r.payment_id
WHERE r.status = 'COMPLETED' AND r.amount < p.amount
UNION ALL
SELECT 'TEACHING', 'full refund var', count(*)::bigint, count(*) > 0, 'gross vs net revenue'
FROM refunds r JOIN payments p ON p.id = r.payment_id
WHERE r.status = 'COMPLETED' AND r.amount = p.amount
UNION ALL
SELECT 'TEACHING', 'NULL phone tasiyan user var', count(*)::bigint, count(*) > 0, 'NULL semantics'
FROM users WHERE phone IS NULL
UNION ALL
SELECT 'TEACHING', 'delivered_at NULL olan shipment var', count(*)::bigint, count(*) > 0, 'NULL semantics'
FROM shipments WHERE delivered_at IS NULL
UNION ALL
SELECT 'TEACHING', 'tracking_code NULL olan shipment var', count(*)::bigint, count(*) > 0, 'COALESCE / IS NULL'
FROM shipments WHERE tracking_code IS NULL
UNION ALL
SELECT 'TEACHING', 'hicbir kategoriye bagli olmayan product var', count(*)::bigint, count(*) > 0, 'junction + LEFT JOIN'
FROM products p WHERE NOT EXISTS (SELECT 1 FROM product_categories pc WHERE pc.product_id = p.id)
UNION ALL
SELECT 'TEACHING', 'category hierarchy en az 4 seviye', max(depth)::bigint, max(depth) >= 4, 'recursive CTE'
FROM (WITH RECURSIVE t AS (
         SELECT id, 1 AS depth FROM categories WHERE parent_id IS NULL
         UNION ALL
         SELECT c.id, t.depth + 1 FROM categories c JOIN t ON c.parent_id = t.id)
      SELECT depth FROM t) e
UNION ALL
SELECT 'TEACHING', 'pasif merchant membership var', count(*)::bigint, count(*) > 0, 'authorization correctness'
FROM merchant_members WHERE is_active = false
UNION ALL
SELECT 'TEACHING', 'birden fazla merchant''a uye user var', count(*)::bigint, count(*) > 0, 'authorization composition'
FROM (SELECT user_id FROM merchant_members GROUP BY user_id HAVING count(DISTINCT merchant_id) > 1) f
UNION ALL
SELECT 'TEACHING', 'guncel fiyati siparis fiyatindan farkli item var', count(*)::bigint, count(*) > 0,
       'historical price vs current price'
FROM order_items oi JOIN products p ON p.id = oi.product_id
WHERE oi.unit_price <> p.price
UNION ALL
SELECT 'TEACHING', 'provider_response NULL olan payment var', count(*)::bigint, count(*) > 0, 'JSONB + NULL'
FROM payments WHERE provider_response IS NULL
$$;

-- ---------------------------------------------------------------------
-- Sonuclar
-- ---------------------------------------------------------------------
SELECT kind,
       check_name,
       actual,
       CASE WHEN ok THEN 'PASS' ELSE 'FAIL' END AS status,
       note
FROM verify_seed()
ORDER BY kind, ok, check_name;

-- ---------------------------------------------------------------------
-- Ozet + basarisizsa hata firlat (ON_ERROR_STOP ile birlikte kullan)
-- ---------------------------------------------------------------------
DO $$
DECLARE
    n_fail integer;
    fails  text;
BEGIN
    SELECT count(*), string_agg(check_name, '; ' ORDER BY check_name)
    INTO n_fail, fails
    FROM verify_seed() WHERE NOT ok;

    IF n_fail > 0 THEN
        RAISE EXCEPTION 'SEED DOGRULAMA BASARISIZ (% kontrol): %', n_fail, fails;
    END IF;

    RAISE NOTICE 'Seed dogrulama basarili. Dataset kullanima hazir.';
END;
$$;
