-- =====================================================================
-- CommerceOps · 00_schema.sql
-- Practical SQL Query Engineering — dataset v1
--
-- Bu dosya SADECE schema ve table tanimlarini icerir.
-- Foreign key ve check constraint'ler  -> 01_constraints.sql
-- Baseline index'ler                   -> 02_indexes_baseline.sql
--
-- Calistirma sirasi:
--   00_schema.sql -> 01_constraints.sql -> 02_indexes_baseline.sql
--   -> 10_reference_data.sql -> (11_seed_small.sql | 12_seed_full.sql)
--   -> 14_verify_seed.sql -> 15_analyze.sql
--
-- Not: Tablolar public degil, commerceops schema'sinda yasar.
--      Bu bilincli bir tercih: search_path ve qualified name calismasi icin.
-- =====================================================================

DROP SCHEMA IF EXISTS commerceops CASCADE;
CREATE SCHEMA commerceops;

SET search_path = commerceops, public;

-- ---------------------------------------------------------------------
-- Dataset metadata
-- ---------------------------------------------------------------------
CREATE TABLE dataset_info (
    id              integer PRIMARY KEY DEFAULT 1,
    dataset_version text        NOT NULL,
    profile         text        NOT NULL,
    generated_at    timestamptz NOT NULL,
    notes           text
);
COMMENT ON TABLE dataset_info IS 'Yuklu dataset profile ve version bilgisi. Her seed sonrasi tek satir.';

-- ---------------------------------------------------------------------
-- Identity and merchant access
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text        NOT NULL,
    full_name     text        NOT NULL,
    phone         text,                                   -- nullable: kontrollu oranda NULL
    status        text        NOT NULL DEFAULT 'ACTIVE',
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz                             -- nullable: hic giris yapmamis user
);
COMMENT ON TABLE users IS 'Customer ve/veya merchant calisani olabilen sistem kullanicilari.';

CREATE TABLE merchants (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text          NOT NULL,
    slug            text          NOT NULL,
    status          text          NOT NULL DEFAULT 'ACTIVE',
    commission_rate numeric(5,4)  NOT NULL DEFAULT 0.1000,
    country_code    char(2)       NOT NULL DEFAULT 'TR',
    created_at      timestamptz   NOT NULL DEFAULT now()
);
COMMENT ON TABLE merchants IS 'Marketplace uzerinde urun satan isletmeler.';

CREATE TABLE merchant_members (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id bigint      NOT NULL,
    user_id     bigint      NOT NULL,
    role        text        NOT NULL,          -- OWNER | MANAGER | ANALYST | OPERATOR
    is_active   boolean     NOT NULL DEFAULT true,
    joined_at   timestamptz NOT NULL,
    ended_at    timestamptz                    -- nullable: hala aktif uyelik
);
COMMENT ON TABLE merchant_members IS 'User-merchant uyeligi ve rolu. Authorization query''lerinin temeli.';

CREATE TABLE addresses (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint      NOT NULL,
    label          text        NOT NULL,
    recipient_name text        NOT NULL,
    line1          text        NOT NULL,
    line2          text,
    city           text        NOT NULL,
    postal_code    text,
    country_code   char(2)     NOT NULL DEFAULT 'TR',
    is_default     boolean     NOT NULL DEFAULT false,
    created_at     timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE addresses IS 'Kullanicinin kayitli adresleri. Order snapshot adresi ile karistirilmaz.';

-- ---------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------
CREATE TABLE categories (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  bigint,                          -- self-reference, NULL = root
    name       text        NOT NULL,
    slug       text        NOT NULL,
    is_active  boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE categories IS 'Cok seviyeli category hierarchy. Recursive CTE calismasinin kaynagi.';

CREATE TABLE products (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id     bigint        NOT NULL,
    sku             text          NOT NULL,
    name            text          NOT NULL,
    description     text,                        -- nullable
    status          text          NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | DRAFT | ARCHIVED
    price           numeric(12,2) NOT NULL,      -- GUNCEL fiyat; order total'da kullanilmaz
    currency        char(3)       NOT NULL DEFAULT 'TRY',
    track_inventory boolean       NOT NULL DEFAULT true,
    weight_grams    integer,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    updated_at      timestamptz   NOT NULL DEFAULT now()
);
COMMENT ON COLUMN products.price IS 'Guncel liste fiyati. Tarihsel order total icin order_items.unit_price kullanilir.';

CREATE TABLE product_categories (
    product_id  bigint      NOT NULL,
    category_id bigint      NOT NULL,
    is_primary  boolean     NOT NULL DEFAULT false,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (product_id, category_id)
);
COMMENT ON TABLE product_categories IS 'Many-to-many junction. Sadece teknik ara tablo degil: is_primary attribute tasir.';

-- ---------------------------------------------------------------------
-- Ordering
-- ---------------------------------------------------------------------
CREATE TABLE orders (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number         text        NOT NULL,
    customer_id          bigint      NOT NULL,
    status               text        NOT NULL,   -- PENDING|PAID|PROCESSING|SHIPPED|DELIVERED|CANCELLED
    currency             char(3)     NOT NULL DEFAULT 'TRY',
    placed_at            timestamptz NOT NULL,
    created_at           timestamptz NOT NULL,
    updated_at           timestamptz NOT NULL,
    shipping_address_id  bigint,                 -- nullable: adres silinmis olabilir
    ship_recipient_name  text        NOT NULL,   -- snapshot
    ship_line1           text        NOT NULL,   -- snapshot
    ship_city            text        NOT NULL,   -- snapshot
    ship_postal_code     text,                   -- snapshot
    ship_country_code    char(2)     NOT NULL,   -- snapshot
    customer_note        text
);
COMMENT ON TABLE orders IS 'Marketplace siparisi. Order total kolonu YOKTUR; order_items''tan hesaplanir.';
COMMENT ON COLUMN orders.ship_line1 IS 'Siparis anindaki adres snapshot''i. addresses tablosu degisse bile degismez.';

CREATE TABLE order_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint        NOT NULL,
    product_id      bigint        NOT NULL,
    merchant_id     bigint        NOT NULL,   -- siparis anindaki satici
    quantity        integer       NOT NULL,
    unit_price      numeric(12,2) NOT NULL,   -- siparis anindaki fiyat (snapshot)
    discount_amount numeric(12,2) NOT NULL DEFAULT 0,
    created_at      timestamptz   NOT NULL
);
COMMENT ON TABLE order_items IS 'Order line. Grain: order + product. Merchant iliskisi order''a degil buraya baglidir.';

CREATE TABLE order_status_history (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          bigint      NOT NULL,
    from_status       text,                   -- nullable: ilk kayit
    to_status         text        NOT NULL,
    changed_at        timestamptz NOT NULL,
    changed_by_user_id bigint,                -- nullable: sistem tarafindan degisti
    note              text
);
COMMENT ON TABLE order_status_history IS 'Event/history tablosu. Grain: order + status degisimi.';

-- ---------------------------------------------------------------------
-- Payment and refund
-- ---------------------------------------------------------------------
CREATE TABLE payments (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          bigint        NOT NULL,
    provider          text          NOT NULL,   -- ADYEN | STRIPE | LOCAL_BANK | WALLET
    attempt_no        integer       NOT NULL,
    status            text          NOT NULL,   -- PENDING | SUCCEEDED | FAILED | CANCELLED
    amount            numeric(12,2) NOT NULL,
    currency          char(3)       NOT NULL DEFAULT 'TRY',
    created_at        timestamptz   NOT NULL,
    settled_at        timestamptz,              -- nullable: sadece SUCCEEDED icin dolu
    failure_code      text,                     -- nullable: sadece FAILED icin dolu
    provider_response jsonb                     -- JSONB query calismasi icin
);
COMMENT ON TABLE payments IS 'Order basina birden fazla attempt. Revenue sadece SUCCEEDED kayitlardan hesaplanir.';

CREATE TABLE refunds (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id    bigint        NOT NULL,
    order_item_id bigint,                     -- nullable: order-level refund
    amount        numeric(12,2) NOT NULL,
    reason        text,                       -- nullable
    status        text          NOT NULL DEFAULT 'COMPLETED',  -- PENDING|COMPLETED|REJECTED
    created_at    timestamptz   NOT NULL,
    processed_at  timestamptz
);
COMMENT ON TABLE refunds IS 'Bir payment birden fazla partial refund alabilir. Gross ile karistirilmaz.';

-- ---------------------------------------------------------------------
-- Inventory and fulfillment
-- ---------------------------------------------------------------------
CREATE TABLE warehouses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id  bigint      NOT NULL,
    code         text        NOT NULL,
    name         text        NOT NULL,
    city         text        NOT NULL,
    country_code char(2)     NOT NULL DEFAULT 'TR',
    is_active    boolean     NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE inventory_movements (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id   bigint      NOT NULL,
    product_id     bigint      NOT NULL,
    movement_type  text        NOT NULL,   -- INBOUND | OUTBOUND | RETURN | ADJUSTMENT
    quantity       integer     NOT NULL,   -- ISARETLI: giris +, cikis -
    occurred_at    timestamptz NOT NULL,
    reference_type text,                   -- SHIPMENT_ITEM | REFUND | MANUAL
    reference_id   bigint,
    metadata       jsonb,
    created_at     timestamptz NOT NULL
);
COMMENT ON COLUMN inventory_movements.quantity IS 'Isaretli miktar. On-hand = SUM(quantity). Ayri stok kolonu yoktur.';

CREATE TABLE shipments (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint      NOT NULL,
    warehouse_id  bigint,                 -- nullable: merchant''in warehouse kaydi olmayabilir
    carrier       text        NOT NULL,
    tracking_code text,                   -- nullable: henuz olusmamis
    status        text        NOT NULL,   -- PENDING|DISPATCHED|IN_TRANSIT|DELIVERED|RETURNED|CANCELLED
    shipped_at    timestamptz,            -- nullable
    delivered_at  timestamptz,            -- nullable
    created_at    timestamptz NOT NULL
);

CREATE TABLE shipment_items (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id   bigint  NOT NULL,
    order_item_id bigint  NOT NULL,
    quantity      integer NOT NULL
);
COMMENT ON TABLE shipment_items IS 'Order item''larin shipment''lara dagilimi. Kismi gonderim mumkundur.';

-- ---------------------------------------------------------------------
-- Customer feedback
-- ---------------------------------------------------------------------
CREATE TABLE reviews (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    bigint    NOT NULL,
    user_id       bigint    NOT NULL,
    order_item_id bigint,
    rating        integer   NOT NULL,
    title         text,
    body          text,
    is_verified   boolean   NOT NULL DEFAULT true,
    submitted_at  timestamp NOT NULL,        -- BILINCLI: timestamp WITHOUT time zone
    created_at    timestamptz NOT NULL
);
COMMENT ON COLUMN reviews.submitted_at IS 'Bilincli olarak timestamp WITHOUT time zone. timestamptz farki calismasi icin.';
