-- =====================================================================
-- CommerceOps · schema.sql
-- Practical SQL Query Engineering — dataset v1
--
-- Bu dosya schema, table, constraint ve baseline index tanimlarinin
-- TAMAMINI icerir.
--
-- Duzen: her tablonun unique / check / foreign key constraint'leri
-- dogrudan CREATE TABLE govdesinde, isimlendirilmis CONSTRAINT olarak
-- tanimlidir. Index'ler constraint olmadigi icin tablonun hemen
-- altinda CREATE INDEX ile gelir.
--
-- Tablo sirasi topolojiktir: her foreign key'in hedef tablosu daha once
-- yaratilmis olur. Bu sayede FK'ler ALTER TABLE'a gerek kalmadan tablo
-- govdesinde tanimlanabiliyor.
--   NOT: ileride iki tablo birbirine karsilikli FK verirse (dongu),
--   o zaman donguyu kiran taraf ALTER TABLE ... ADD CONSTRAINT ile
--   dosyanin sonuna alinmak zorundadir. Su an dongu yok.
--
-- Calistirma sirasi:
--   schema.sql
--   -> 10_reference_data.sql -> (11_seed_small.sql | 12_seed_full.sql)
--   -> 14_verify_seed.sql -> 15_analyze.sql
--
-- Not: Tablolar public degil, commerceops schema'sinda yasar.
--      Bu bilincli bir tercih: search_path ve qualified name calismasi icin.
-- =====================================================================

DROP SCHEMA IF EXISTS commerceops CASCADE;
CREATE SCHEMA commerceops;

SET search_path = commerceops, public;


-- =====================================================================
-- Dataset metadata
-- =====================================================================

-- ---------------------------------------------------------------------
-- dataset_info
-- ---------------------------------------------------------------------
CREATE TABLE dataset_info (
    id              integer PRIMARY KEY DEFAULT 1,
    dataset_version text        NOT NULL,
    profile         text        NOT NULL,
    generated_at    timestamptz NOT NULL,
    notes           text
);
COMMENT ON TABLE dataset_info IS 'Yuklu dataset profile ve version bilgisi. Her seed sonrasi tek satir.';


-- =====================================================================
-- Identity and merchant access
-- =====================================================================

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text        NOT NULL,
    full_name     text        NOT NULL,
    phone         text,                                   -- nullable: kontrollu oranda NULL
    status        text        NOT NULL DEFAULT 'ACTIVE',
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz,                            -- nullable: hic giris yapmamis user

    CONSTRAINT uq_users_email  UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE','SUSPENDED','DELETED'))
);
COMMENT ON TABLE users IS 'Customer ve/veya merchant calisani olabilen sistem kullanicilari.';

-- ---------------------------------------------------------------------
-- merchants
-- ---------------------------------------------------------------------
CREATE TABLE merchants (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text          NOT NULL,
    slug            text          NOT NULL,
    status          text          NOT NULL DEFAULT 'ACTIVE',
    commission_rate numeric(5,4)  NOT NULL DEFAULT 0.1000,
    country_code    char(2)       NOT NULL DEFAULT 'TR',
    created_at      timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT uq_merchants_slug  UNIQUE (slug),
    CONSTRAINT ck_merchants_status CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED'))
);
COMMENT ON TABLE merchants IS 'Marketplace uzerinde urun satan isletmeler.';

-- ---------------------------------------------------------------------
-- merchant_members
-- ---------------------------------------------------------------------
CREATE TABLE merchant_members (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id bigint      NOT NULL,
    user_id     bigint      NOT NULL,
    role        text        NOT NULL,          -- OWNER | MANAGER | ANALYST | OPERATOR
    is_active   boolean     NOT NULL DEFAULT true,
    joined_at   timestamptz NOT NULL,
    ended_at    timestamptz,                   -- nullable: hala aktif uyelik

    CONSTRAINT uq_member_merchant_user UNIQUE (merchant_id, user_id),
    CONSTRAINT ck_member_role CHECK (role IN ('OWNER','MANAGER','ANALYST','OPERATOR')),
    CONSTRAINT fk_member_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id),
    CONSTRAINT fk_member_user     FOREIGN KEY (user_id)     REFERENCES users(id)
);
COMMENT ON TABLE merchant_members IS 'User-merchant uyeligi ve rolu. Authorization query''lerinin temeli.';

CREATE INDEX idx_member_user ON merchant_members(user_id);

-- ---------------------------------------------------------------------
-- addresses
-- ---------------------------------------------------------------------
CREATE TABLE addresses (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint      NOT NULL,
    label          text        NOT NULL,
    recipient_name text        NOT NULL,
    line1          text        NOT NULL,
    line2          text,
    city           text        NOT NULL,
    postal_code    text,
    country_code   char(2)     NOT NULL DEFAULT 'TR',
    is_default     boolean     NOT NULL DEFAULT false,
    created_at     timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users(id)
);
COMMENT ON TABLE addresses IS 'Kullanicinin kayitli adresleri. Order snapshot adresi ile karistirilmaz.';

CREATE INDEX idx_addresses_user ON addresses(user_id);


-- =====================================================================
-- Catalog
-- =====================================================================

-- ---------------------------------------------------------------------
-- categories
--   parent_id kendi tablosuna FK verir; CREATE TABLE govdesinde
--   self-reference tanimlamak gecerlidir.
-- ---------------------------------------------------------------------
CREATE TABLE categories (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  bigint,                          -- self-reference, NULL = root
    name       text        NOT NULL,
    slug       text        NOT NULL,
    is_active  boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_categories_slug UNIQUE (slug),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);
COMMENT ON TABLE categories IS 'Cok seviyeli category hierarchy. Recursive CTE calismasinin kaynagi.';

CREATE INDEX idx_categories_parent ON categories(parent_id);

-- ---------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------
CREATE TABLE products (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id     bigint        NOT NULL,
    sku             text          NOT NULL,
    name            text          NOT NULL,
    description     text,                        -- nullable
    status          text          NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | DRAFT | ARCHIVED
    price           numeric(12,2) NOT NULL,      -- GUNCEL fiyat; order total'da kullanilmaz
    currency        char(3)       NOT NULL DEFAULT 'TRY',
    track_inventory boolean       NOT NULL DEFAULT true,
    weight_grams    integer,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    updated_at      timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT uq_products_sku    UNIQUE (sku),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE','DRAFT','ARCHIVED')),
    CONSTRAINT ck_products_price  CHECK (price >= 0),
    CONSTRAINT fk_products_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id)
);
COMMENT ON COLUMN products.price IS 'Guncel liste fiyati. Tarihsel order total icin order_items.unit_price kullanilir.';

CREATE INDEX idx_products_merchant ON products(merchant_id);

-- ---------------------------------------------------------------------
-- product_categories
-- ---------------------------------------------------------------------
CREATE TABLE product_categories (
    product_id  bigint      NOT NULL,
    category_id bigint      NOT NULL,
    is_primary  boolean     NOT NULL DEFAULT false,
    assigned_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_pc_product  FOREIGN KEY (product_id)  REFERENCES products(id),
    CONSTRAINT fk_pc_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
COMMENT ON TABLE product_categories IS 'Many-to-many junction. Sadece teknik ara tablo degil: is_primary attribute tasir.';

CREATE INDEX idx_pc_category ON product_categories(category_id);


-- =====================================================================
-- Ordering
-- =====================================================================

-- ---------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------
CREATE TABLE orders (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number         text        NOT NULL,
    customer_id          bigint      NOT NULL,
    status               text        NOT NULL,   -- PENDING|PAID|PROCESSING|SHIPPED|DELIVERED|CANCELLED
    currency             char(3)     NOT NULL DEFAULT 'TRY',
    placed_at            timestamptz NOT NULL,
    created_at           timestamptz NOT NULL,
    updated_at           timestamptz NOT NULL,
    shipping_address_id  bigint,                 -- nullable: adres silinmis olabilir
    ship_recipient_name  text        NOT NULL,   -- snapshot
    ship_line1           text        NOT NULL,   -- snapshot
    ship_city            text        NOT NULL,   -- snapshot
    ship_postal_code     text,                   -- snapshot
    ship_country_code    char(2)     NOT NULL,   -- snapshot
    customer_note        text,

    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED')),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)         REFERENCES users(id),
    CONSTRAINT fk_orders_address  FOREIGN KEY (shipping_address_id) REFERENCES addresses(id)
);
COMMENT ON TABLE orders IS 'Marketplace siparisi. Order total kolonu YOKTUR; order_items''tan hesaplanir.';
COMMENT ON COLUMN orders.ship_line1 IS 'Siparis anindaki adres snapshot''i. addresses tablosu degisse bile degismez.';

CREATE INDEX idx_orders_customer ON orders(customer_id);

-- ---------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------
CREATE TABLE order_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint        NOT NULL,
    product_id      bigint        NOT NULL,
    merchant_id     bigint        NOT NULL,   -- siparis anindaki satici
    quantity        integer       NOT NULL,
    unit_price      numeric(12,2) NOT NULL,   -- siparis anindaki fiyat (snapshot)
    discount_amount numeric(12,2) NOT NULL DEFAULT 0,
    created_at      timestamptz   NOT NULL,

    CONSTRAINT uq_order_item_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_items_quantity   CHECK (quantity > 0),
    CONSTRAINT ck_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_items_discount   CHECK (discount_amount >= 0),
    CONSTRAINT fk_items_order    FOREIGN KEY (order_id)    REFERENCES orders(id),
    CONSTRAINT fk_items_product  FOREIGN KEY (product_id)  REFERENCES products(id),
    CONSTRAINT fk_items_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id)
);
COMMENT ON TABLE order_items IS 'Order line. Grain: order + product. Merchant iliskisi order''a degil buraya baglidir.';

CREATE INDEX idx_items_order   ON order_items(order_id);
CREATE INDEX idx_items_product ON order_items(product_id);

-- ---------------------------------------------------------------------
-- order_status_history
-- ---------------------------------------------------------------------
CREATE TABLE order_status_history (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          bigint      NOT NULL,
    from_status       text,                   -- nullable: ilk kayit
    to_status         text        NOT NULL,
    changed_at        timestamptz NOT NULL,
    changed_by_user_id bigint,                -- nullable: sistem tarafindan degisti
    note              text,

    CONSTRAINT ck_history_status CHECK (to_status IN ('PENDING','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED')),
    CONSTRAINT fk_history_order FOREIGN KEY (order_id)           REFERENCES orders(id),
    CONSTRAINT fk_history_user  FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
);
COMMENT ON TABLE order_status_history IS 'Event/history tablosu. Grain: order + status degisimi.';

CREATE INDEX idx_history_order ON order_status_history(order_id);


-- =====================================================================
-- Payment and refund
-- =====================================================================

-- ---------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------
CREATE TABLE payments (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          bigint        NOT NULL,
    provider          text          NOT NULL,   -- ADYEN | STRIPE | LOCAL_BANK | WALLET
    attempt_no        integer       NOT NULL,
    status            text          NOT NULL,   -- PENDING | SUCCEEDED | FAILED | CANCELLED
    amount            numeric(12,2) NOT NULL,
    currency          char(3)       NOT NULL DEFAULT 'TRY',
    created_at        timestamptz   NOT NULL,
    settled_at        timestamptz,              -- nullable: sadece SUCCEEDED icin dolu
    failure_code      text,                     -- nullable: sadece FAILED icin dolu
    provider_response jsonb,                    -- JSONB query calismasi icin

    CONSTRAINT uq_payment_order_attempt UNIQUE (order_id, attempt_no),
    CONSTRAINT ck_payments_status   CHECK (status IN ('PENDING','SUCCEEDED','FAILED','CANCELLED')),
    CONSTRAINT ck_payments_provider CHECK (provider IN ('ADYEN','STRIPE','LOCAL_BANK','WALLET')),
    CONSTRAINT ck_payments_attempt  CHECK (attempt_no >= 1),
    CONSTRAINT ck_payments_settled  CHECK ((status =  'SUCCEEDED' AND settled_at IS NOT NULL)
                                        OR (status <> 'SUCCEEDED' AND settled_at IS NULL)),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
COMMENT ON TABLE payments IS 'Order basina birden fazla attempt. Revenue sadece SUCCEEDED kayitlardan hesaplanir.';

CREATE INDEX idx_payments_order ON payments(order_id);

-- ---------------------------------------------------------------------
-- refunds
-- ---------------------------------------------------------------------
CREATE TABLE refunds (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id    bigint        NOT NULL,
    order_item_id bigint,                     -- nullable: order-level refund
    amount        numeric(12,2) NOT NULL,
    reason        text,                       -- nullable
    status        text          NOT NULL DEFAULT 'COMPLETED',  -- PENDING|COMPLETED|REJECTED
    created_at    timestamptz   NOT NULL,
    processed_at  timestamptz,

    CONSTRAINT ck_refunds_status CHECK (status IN ('PENDING','COMPLETED','REJECTED')),
    CONSTRAINT ck_refunds_amount CHECK (amount > 0),
    CONSTRAINT fk_refunds_payment    FOREIGN KEY (payment_id)    REFERENCES payments(id),
    CONSTRAINT fk_refunds_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id)
);
COMMENT ON TABLE refunds IS 'Bir payment birden fazla partial refund alabilir. Gross ile karistirilmaz.';

CREATE INDEX idx_refunds_payment ON refunds(payment_id);


-- =====================================================================
-- Inventory and fulfillment
-- =====================================================================

-- ---------------------------------------------------------------------
-- warehouses
-- ---------------------------------------------------------------------
CREATE TABLE warehouses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id  bigint      NOT NULL,
    code         text        NOT NULL,
    name         text        NOT NULL,
    city         text        NOT NULL,
    country_code char(2)     NOT NULL DEFAULT 'TR',
    is_active    boolean     NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_warehouses_code UNIQUE (code),
    CONSTRAINT fk_warehouses_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id)
);

CREATE INDEX idx_warehouses_merchant ON warehouses(merchant_id);

-- ---------------------------------------------------------------------
-- inventory_movements
-- ---------------------------------------------------------------------
CREATE TABLE inventory_movements (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id   bigint      NOT NULL,
    product_id     bigint      NOT NULL,
    movement_type  text        NOT NULL,   -- INBOUND | OUTBOUND | RETURN | ADJUSTMENT
    quantity       integer     NOT NULL,   -- ISARETLI: giris +, cikis -
    occurred_at    timestamptz NOT NULL,
    reference_type text,                   -- SHIPMENT_ITEM | REFUND | MANUAL
    reference_id   bigint,
    metadata       jsonb,
    created_at     timestamptz NOT NULL,

    CONSTRAINT ck_movement_type CHECK (movement_type IN ('INBOUND','OUTBOUND','RETURN','ADJUSTMENT')),
    CONSTRAINT ck_movement_sign CHECK (
        (movement_type IN ('INBOUND','RETURN') AND quantity > 0)
     OR (movement_type = 'OUTBOUND'           AND quantity < 0)
     OR (movement_type = 'ADJUSTMENT'         AND quantity <> 0)
    ),
    CONSTRAINT fk_movements_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_movements_product   FOREIGN KEY (product_id)   REFERENCES products(id)
);
COMMENT ON COLUMN inventory_movements.quantity IS 'Isaretli miktar. On-hand = SUM(quantity). Ayri stok kolonu yoktur.';

CREATE INDEX idx_movements_product   ON inventory_movements(product_id);
CREATE INDEX idx_movements_warehouse ON inventory_movements(warehouse_id);

-- ---------------------------------------------------------------------
-- shipments
-- ---------------------------------------------------------------------
CREATE TABLE shipments (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint      NOT NULL,
    warehouse_id  bigint,                 -- nullable: merchant''in warehouse kaydi olmayabilir
    carrier       text        NOT NULL,
    tracking_code text,                   -- nullable: henuz olusmamis
    status        text        NOT NULL,   -- PENDING|DISPATCHED|IN_TRANSIT|DELIVERED|RETURNED|CANCELLED
    shipped_at    timestamptz,            -- nullable
    delivered_at  timestamptz,            -- nullable
    created_at    timestamptz NOT NULL,

    CONSTRAINT ck_shipments_status CHECK (status IN ('PENDING','DISPATCHED','IN_TRANSIT','DELIVERED','RETURNED','CANCELLED')),
    CONSTRAINT fk_shipments_order     FOREIGN KEY (order_id)     REFERENCES orders(id),
    CONSTRAINT fk_shipments_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE INDEX idx_shipments_order ON shipments(order_id);

-- ---------------------------------------------------------------------
-- shipment_items
-- ---------------------------------------------------------------------
CREATE TABLE shipment_items (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id   bigint  NOT NULL,
    order_item_id bigint  NOT NULL,
    quantity      integer NOT NULL,

    CONSTRAINT uq_shipment_item_pair  UNIQUE (shipment_id, order_item_id),
    CONSTRAINT ck_shipitems_quantity  CHECK (quantity > 0),
    CONSTRAINT fk_shipitems_shipment   FOREIGN KEY (shipment_id)   REFERENCES shipments(id),
    CONSTRAINT fk_shipitems_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id)
);
COMMENT ON TABLE shipment_items IS 'Order item''larin shipment''lara dagilimi. Kismi gonderim mumkundur.';

CREATE INDEX idx_shipitems_shipment   ON shipment_items(shipment_id);
CREATE INDEX idx_shipitems_order_item ON shipment_items(order_item_id);


-- =====================================================================
-- Customer feedback
-- =====================================================================

-- ---------------------------------------------------------------------
-- reviews
-- ---------------------------------------------------------------------
CREATE TABLE reviews (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    bigint    NOT NULL,
    user_id       bigint    NOT NULL,
    order_item_id bigint,
    rating        integer   NOT NULL,
    title         text,
    body          text,
    is_verified   boolean   NOT NULL DEFAULT true,
    submitted_at  timestamp NOT NULL,        -- BILINCLI: timestamp WITHOUT time zone
    created_at    timestamptz NOT NULL,

    CONSTRAINT uq_review_product_user UNIQUE (product_id, user_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_reviews_product    FOREIGN KEY (product_id)    REFERENCES products(id),
    CONSTRAINT fk_reviews_user       FOREIGN KEY (user_id)       REFERENCES users(id),
    CONSTRAINT fk_reviews_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id)
);
COMMENT ON COLUMN reviews.submitted_at IS 'Bilincli olarak timestamp WITHOUT time zone. timestamptz farki calismasi icin.';

CREATE INDEX idx_reviews_product ON reviews(product_id);


-- =====================================================================
-- BASELINE INDEX NOTU
--
-- Yukaridaki index seti BILINCLI olarak EKSIKTIR.
--
-- Amac "iyi indexlenmis bir veritabani" vermek degil; Module 9'da olcumle
-- index degerlendirmesi yapabilecegin gercekci bir baslangic noktasi vermek.
--
-- Kural: index onerisi full dataset uzerinde EXPLAIN ANALYZE olcumu
--        olmadan yapilmaz.
--
-- BILEREK EKLENMEYENLER (Module 9'da olcup kendin karar vereceksin):
--
--   order_items(merchant_id)              -> merchant order list endpoint'inin kalbi
--   orders(placed_at) / orders(created_at)-> tarih araligi raporlari
--   orders(status)                        -> status filtresi
--   payments(status, settled_at)          -> revenue reporting
--   products(name) / trigram index        -> product search
--   inventory_movements(occurred_at)      -> hareket zaman araligi
--   payments(provider_response) GIN       -> JSONB sorgulari
--   composite key-set pagination index    -> (merchant, created_at DESC, id DESC)
--
-- Bunlarin hicbirini simdiden ekleme. Once dogru query, sonra olcum.
-- =====================================================================
