-- Apply all three schema files in order, in one transaction.
CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    name varchar(200) NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint,
    name varchar(120) NOT NULL
);
CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL,
    name varchar(200) NOT NULL,
    price numeric(12,2) NOT NULL,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE TABLE order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL
);
CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    status varchar(20) NOT NULL,
    amount numeric(12,2) NOT NULL,
    provider varchar(40) NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE TABLE shipments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    status varchar(20) NOT NULL,
    shipped_at timestamptz,
    delivered_at timestamptz
);
CREATE TABLE order_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    status varchar(20) NOT NULL,
    changed_at timestamptz NOT NULL
);
CREATE TABLE inventory_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    quantity_delta integer NOT NULL,
    reason varchar(30) NOT NULL,
    created_at timestamptz NOT NULL
);
